# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('direction', models.IntegerField(choices=[(1, 'data provider'), (0, 'data consumer')])),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_value', models.FloatField()),
                ('operator', models.SmallIntegerField(choices=[('<', 'less than'), ('<=', 'less than or equal'), ('>', 'greater than'), ('>=', 'greater than or equal'), ('=', 'equal'), ('!=', 'not equal')])),
            ],
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.CharField(max_length=100)),
                ('target_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.Device')),
            ],
        ),
        migrations.AddField(
            model_name='rule',
            name='ruleset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='workshop.RuleSet'),
        ),
        migrations.AddField(
            model_name='rule',
            name='source_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.Device'),
        ),
    ]
