# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='operator',
            field=models.CharField(choices=[('<', 'less than'), ('<=', 'less than or equal'), ('>', 'greater than'), ('>=', 'greater than or equal'), ('=', 'equal'), ('!=', 'not equal')], max_length=10),
        ),
    ]
