# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_auto_20171110_2136'),
        ('workshop', '0002_messagehistory_timestamp'),
    ]

    operations = [
    ]
