# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_merge_20171111_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
