# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 08:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop', '0005_merge_20171111_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagehistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
